### ISSUE TITLE
Support for RK3399

### ISSUE THREAD

**Issue by jalr** [linuxerwang/rkflashkit#11]
I'm trying to get my brand new RK3399 flashed
simply adding the missing device id 2207:330c didn't work, when I do a rkflashkit reboot, I get:
```
Found devices:
0x2207:0x330c
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=2
Traceback (most recent call last):
  File "/usr/bin/rkflashkit", line 17, in <module>
    sys.exit(app.main(sys.argv[1:]))
  File "/usr/share/rkflashkit/lib/rkflashkit/climain.py", line 99, in main
    self.parse_and_execute(args)
  File "/usr/share/rkflashkit/lib/rkflashkit/climain.py", line 130, in parse_and_execute
    self.reboot()
  File "/usr/share/rkflashkit/lib/rkflashkit/climain.py", line 205, in reboot
    op.reboot()
  File "/usr/share/rkflashkit/lib/rkflashkit/rktalk.py", line 359, in reboot
    self.__init_device()
  File "/usr/share/rkflashkit/lib/rkflashkit/rktalk.py", line 128, in __init_device
    2, ''.join(prepare_cmd(0x80, 0x00060000, 0x00000000, 0x00000000)))
  File "/usr/share/rkflashkit/lib/rkflashkit/usb1.py", line 1145, in bulkWrite
    return self._bulkTransfer(endpoint, data, sizeof(data), timeout)
  File "/usr/share/rkflashkit/lib/rkflashkit/usb1.py", line 1129, in _bulkTransfer
    raise libusb1.USBError(result)
rkflashkit.libusb1.USBError: LIBUSB_ERROR_IO [-1]
```

**Comment by linuxerwang** [comment]
Sorry about that. I don't have any device with rk3399 so I am not sure what's wrong. It seems the USB product id is correct though.

**Comment by tx0h** [comment]
i have the same error. what board do you use?

**Comment by jalr** [comment]
I've got a Firefly RK3399. Currently I'm using rkdeveloptool from https://github.com/rockchip-linux/rkbin in a Docker container. I would be very happy if rkflashkit had support for rk3399.
