### ISSUE TITLE
`LIBUSB_ERROR_IO [-1]`

### ISSUE THREAD

**Issue by FFY00** [linuxerwang/rkflashkit#18]
When trying to connect to a RK3188.

```
Traceback (most recent call last):
  File "/home/anubis/git/rkflashkit/src/rkflashkit/main.py", line 393, in __on_device_changed
    partitions = op.load_partitions()
  File "/home/anubis/git/rkflashkit/src/rkflashkit/rktalk.py", line 190, in load_partitions
    self.__init_device()
  File "/home/anubis/git/rkflashkit/src/rkflashkit/rktalk.py", line 150, in __init_device
    ''.join(prepare_cmd(0x80, 0x00060000, 0x00000000, 0x00000000)))
  File "/home/anubis/git/rkflashkit/src/rkflashkit/usb1.py", line 1145, in bulkWrite
    return self._bulkTransfer(endpoint, data, sizeof(data), timeout)
  File "/home/anubis/git/rkflashkit/src/rkflashkit/usb1.py", line 1129, in _bulkTransfer
    raise libusb1.USBError(result)
rkflashkit.libusb1.USBError: LIBUSB_ERROR_IO [-1]
```

**Comment by eldarkg** [comment]
@FFY00 run as root
