### ISSUE TITLE
rkflashkit.libusb1.USBError: LIBUSB_ERROR_NO_DEVICE [-4]

### ISSUE THREAD

**Issue by pschonmann** [linuxerwang/rkflashkit#8]
After unsuccesfull upgrade from windows im trying way to make stick again working. Seems that NAND was overwriten. Using MK802IIIS. This is output when im using tool in recovery mode. Windows cant detect USB. Error 43.

============= 2016-10-24 17:09:40 ============

	Reading flash information
	Loading partition information
Traceback (most recent call last):
  File "./run.py", line 17, in <module>
    sys.exit(app.main(sys.argv[1:]))
  File "/root/rkflashkit/src/rkflashkit/climain.py", line 99, in main
    self.parse_and_execute(args)
  File "/root/rkflashkit/src/rkflashkit/climain.py", line 106, in parse_and_execute
    self.load_partitions()
  File "/root/rkflashkit/src/rkflashkit/climain.py", line 156, in load_partitions
    loaded_parts = op.load_partitions()
  File "/root/rkflashkit/src/rkflashkit/rktalk.py", line 180, in load_partitions
    content = self.__dev_handle.bulkRead(1, PART_BLOCKSIZE)
  File "/root/rkflashkit/src/rkflashkit/usb1.py", line 1159, in bulkRead
    transferred = self._bulkTransfer(endpoint, data, length, timeout)
  File "/root/rkflashkit/src/rkflashkit/usb1.py", line 1129, in _bulkTransfer
    raise libusb1.USBError(result)
rkflashkit.libusb1.USBError: LIBUSB_ERROR_NO_DEVICE [-4]

**Comment by pschonmann** [comment]
Oh Short circuit metod. Sweet
http://touchscreen-apps.blogspot.cz/2013/02/rikomagic-mk802ii-short-circuit.html

**Comment by Lewiscowles1986** [comment]
I get this part way through transfer.

```
rkflashkit.libusb1.USBError: LIBUSB_ERROR_OVERFLOW [-8]
Traceback (most recent call last):
  File "/usr/share/rkflashkit/lib/rkflashkit/main.py", line 393, in __on_device_changed
    partitions = op.load_partitions()
  File "/usr/share/rkflashkit/lib/rkflashkit/rktalk.py", line 190, in load_partitions
    self.__init_device()
  File "/usr/share/rkflashkit/lib/rkflashkit/rktalk.py", line 151, in __init_device
    self.__dev_handle.bulkRead(self.__read_endpoint, 13)
  File "/usr/share/rkflashkit/lib/rkflashkit/usb1.py", line 1159, in bulkRead
    transferred = self._bulkTransfer(endpoint, data, length, timeout)
  File "/usr/share/rkflashkit/lib/rkflashkit/usb1.py", line 1129, in _bulkTransfer
    raise libusb1.USBError(result)
rkflashkit.libusb1.USBError: LIBUSB_ERROR_IO [-1]
Traceback (most recent call last):
  File "/usr/share/rkflashkit/lib/rkflashkit/main.py", line 393, in __on_device_changed
    partitions = op.load_partitions()
  File "/usr/share/rkflashkit/lib/rkflashkit/rktalk.py", line 190, in load_partitions
    self.__init_device()
  File "/usr/share/rkflashkit/lib/rkflashkit/rktalk.py", line 151, in __init_device
    self.__dev_handle.bulkRead(self.__read_endpoint, 13)
  File "/usr/share/rkflashkit/lib/rkflashkit/usb1.py", line 1159, in bulkRead
    transferred = self._bulkTransfer(endpoint, data, length, timeout)
  File "/usr/share/rkflashkit/lib/rkflashkit/usb1.py", line 1129, in _bulkTransfer
    raise libusb1.USBError(result)
rkflashkit.libusb1.USBError: LIBUSB_ERROR_NO_DEVICE [-4]
^CTraceback (most recent call last):
  File "/usr/bin/rkflashkit", line 21, in <module>
    app.main()
  File "/usr/share/rkflashkit/lib/rkflashkit/main.py", line 421, in main
    gtk.main()
KeyboardInterrupt

```

:cry:
